In [4]:
import sklearn
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# save load_iris() sklearn dataset to iris
# if you'd like to check dataset type use: type(load_iris())
# if you'd like to view list of attributes use: dir(load_iris())
iris = load_iris() 
features = iris.data
#n_sample = len(x)
#print (n_sample)
#print(x)
#print("now with -1")
labels = iris.target
#print(y)
features_train,features_test,labels_train,labels_test=train_test_split(features,labels,test_size=0.5)
print(features_train)
print (len(features_train))
print(labels_train)


[[5.7 3.  4.2 1.2]
 [5.9 3.2 4.8 1.8]
 [7.9 3.8 6.4 2. ]
 [6.7 3.1 4.4 1.4]
 [6.1 2.8 4.7 1.2]
 [4.7 3.2 1.6 0.2]
 [6.3 2.3 4.4 1.3]
 [5.  3.  1.6 0.2]
 [6.3 2.8 5.1 1.5]
 [6.2 3.4 5.4 2.3]
 [7.  3.2 4.7 1.4]
 [4.4 3.  1.3 0.2]
 [6.7 3.  5.2 2.3]
 [6.2 2.9 4.3 1.3]
 [5.  2.  3.5 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [6.5 3.  5.2 2. ]
 [4.6 3.4 1.4 0.3]
 [5.  3.3 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [7.6 3.  6.6 2.1]
 [6.3 2.5 4.9 1.5]
 [6.4 3.2 4.5 1.5]
 [5.6 3.  4.1 1.3]
 [4.9 2.5 4.5 1.7]
 [5.8 4.  1.2 0.2]
 [6.9 3.2 5.7 2.3]
 [5.  3.5 1.6 0.6]
 [5.3 3.7 1.5 0.2]
 [6.8 3.  5.5 2.1]
 [4.6 3.2 1.4 0.2]
 [6.5 3.  5.5 1.8]
 [7.7 2.8 6.7 2. ]
 [5.5 2.3 4.  1.3]
 [6.3 2.7 4.9 1.8]
 [6.3 3.3 4.7 1.6]
 [6.3 2.9 5.6 1.8]
 [6.  3.4 4.5 1.6]
 [6.6 3.  4.4 1.4]
 [5.9 3.  5.1 1.8]
 [6.1 2.9 4.7 1.4]
 [5.7 2.9 4.2 1.3]
 [6.3 3.3 6.  2.5]
 [7.2 3.2 6.  1.8]
 [5.8 2.8 5.1 2.4]
 [4.9 3.  1.4 0.2]
 [6.  2.7 5.1 1.6]
 [5.7 3.8 1.7 0.3]
 [5.8 2.7 3.9 1.2]
 [5.4 3.7 1.5 0.2]
 [5.2 4.1 1.5 0.1]
 [6.  2.2 5.

In [5]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
clf = GaussianNB()
clf.fit(features_train,labels_train)
pred = clf.predict(features_test)
print(accuracy_score(labels_test,pred,  normalize=False))

74


In [6]:
from sklearn import tree
clf_tree = tree.DecisionTreeClassifier()
clf_tree = clf_tree.fit(features_train, labels_train)
pred = clf_tree.predict(features_test)
print(accuracy_score(labels_test,pred,  normalize=False))

71


In [7]:
from sklearn import svm
from sklearn.metrics import accuracy_score
clf_svm = svm.SVC()
clf_svm.fit(features_train,labels_train)
pred = clf_svm.predict(features_test)
print(accuracy_score(labels_test,pred,  normalize=False))

74
